### PR TITLE
Support androidx and fix iOS crash

### LINKED ISSUE #21: Support for androidx
Hi there,
Thanks for your work.
I am trying to use the plugin but I am getting following error:

_OAuthPlugin.java:26: error: cannot find symbol
import android.support.customtabs.CustomTabsIntent;_

Am using volt build (=phonegap build) so I am not compiling anything in my project.

I need to have AndroidXEnabled, is there a chance to upload a new version of the plugin supporting it?

`import androidx.browser.customtabs.CustomTabsIntent;`

thanks,
kind regards

### PR DESCRIPTION
**Pull request by HarelM**
Fixes #21 - support androidx.
After merging this I suggest to release a version with an incremented major number i.e 4.x since this is a breaking change.

### CODE REVIEW

**Comment by HarelM** [comment]
I've also fixed the iOS crash according to #18 as part of this PR.

**Comment by dpogue** [comment]
Thanks for the pull request and for following up with me about it.

My plan is to do this in a few steps:

1. **Merge only the iOS 15 fix to `master` and release v3.0.2**
  This will fix the iOS issue while maintaining compatibility with existing apps.

2. **Cherry pick the iOS 15 fix to `v2.x` and release v2.0.2**
  As requested by some of the folks in #19.

3. **Merge the AndroidX changes and release a new major version v4.0.0**
  Moving to AndroidX is a breaking change, and requires bumping the minimum Cordova Android version to v9.0.0.

Can you check if the CustomTabs stuff in plugin.xml needs to change for AndroidX?
https://github.com/AyogoHealth/cordova-plugin-oauth/blob/71e4f0c58c4b7ac3b0f3f4560a9f7073e15eaa83/plugin.xml#L85-L87

**Comment by HarelM** [comment]
I couldn't find any documentation on that unfortunately...

**Comment by dpogue** [comment]
These have been split up across the various tags/versions as described above and merged, so I'm going to mark this as closed. Thanks for pushing this along.

**Pull request closed without merging**
